const PRODUCTS = [
{id:"straight-bundles",name:"Straight Bundles",category:"Bundles",price:85,image:"assets/straight.jpg",description:"Silky straight bundles with a smooth finish, natural movement and a luxurious look."},
{id:"body-wave-bundles",name:"Body Wave Bundles",category:"Bundles",price:95,image:"assets/body-wave.jpg",description:"Soft, flowing body-wave texture made for versatile everyday glamour."},
{id:"deep-wave-bundles",name:"Deep Wave Bundles",category:"Bundles",price:105,image:"assets/deep-wave.jpg",description:"Defined, full deep-wave texture with beautiful volume and bounce."},
{id:"curly-bundles",name:"Curly Bundles",category:"Bundles",price:105,image:"assets/curly.jpg",description:"Full curly texture with statement volume and a naturally glamorous finish."},
{id:"glueless-lace-wig",name:"Glueless Lace Wig",category:"Wigs",price:180,image:"assets/wig-glueless.jpg",description:"A ready-to-style wig designed for a polished, effortless look."},
{id:"body-wave-wig",name:"Body Wave Wig",category:"Wigs",price:195,image:"assets/wig-body-wave.jpg",description:"A soft body-wave wig with movement, bounce and a timeless silhouette."},
{id:"lace-frontal",name:"Lace Frontal",category:"Frontals & Closures",price:70,image:"assets/lace-frontal.jpg",description:"A versatile lace frontal designed to complete your protective style."},
{id:"hair-care-set",name:"Hair Care Essentials",category:"Hair Care",price:35,image:"assets/hair-care.jpg",description:"A simple care set to help keep your hair routine feeling luxurious."}
];
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
function getCart(){try{return JSON.parse(localStorage.getItem("em-cart")||"[]")}catch{return []}}
function saveCart(cart){localStorage.setItem("em-cart",JSON.stringify(cart));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((sum,i)=>sum+i.qty,0);$$("[data-cart-count]").forEach(el=>el.textContent=n)}
function toast(msg){const el=$(".toast");if(!el)return;el.textContent=msg;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2300)}
function addToCart(id,qty=1){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const cart=getCart();const found=cart.find(x=>x.id===id);if(found)found.qty+=qty;else cart.push({id,qty});saveCart(cart);toast(`${p.name.toUpperCase()} ADDED TO YOUR BAG`)}
function productCard(p){return `<article class="product-card"><a class="product-photo" href="product.html?id=${encodeURIComponent(p.id)}" style="background-image:url('${p.image}')" aria-label="View ${p.name}"><span class="quick-add">VIEW PRODUCT</span></a><h3><a href="product.html?id=${encodeURIComponent(p.id)}">${p.name.toUpperCase()}</a></h3><p class="price">${money(p.price)}</p><button class="btn small" data-add="${p.id}">ADD TO BAG</button></article>`}
function renderProducts(){const featured=$("[data-products='featured']");if(featured){featured.innerHTML=PRODUCTS.slice(0,4).map(productCard).join("");bindAddButtons(featured);}const shop=$("#shopProducts");if(shop){const params=new URLSearchParams(location.search);const initial=params.get("q")||"";const search=$("#productSearch");if(search)search.value=initial;const category=shop.dataset.category||"All";function paint(){const q=(search?.value||"").trim().toLowerCase();const sort=$("#productSort")?.value||"featured";let items=PRODUCTS.filter(p=>(category==="All"||p.category===category)&&(!q||(p.name+" "+p.category+" "+p.description).toLowerCase().includes(q)));if(sort==="price-low")items.sort((a,b)=>a.price-b.price);if(sort==="price-high")items.sort((a,b)=>b.price-a.price);if(sort==="name")items.sort((a,b)=>a.name.localeCompare(b.name));shop.innerHTML=items.length?items.map(productCard).join(""):`<div class="empty-state">No products matched your search. Try another term.</div>`;const count=$("#resultCount");if(count)count.textContent=`${items.length} product${items.length===1?"":"s"}`;bindAddButtons(shop)}search?.addEventListener("input",paint);$("#productSort")?.addEventListener("change",paint);paint()}}
function bindAddButtons(scope=document){$$("[data-add]",scope).forEach(b=>{if(b.dataset.bound)return;b.dataset.bound="1";b.addEventListener("click",()=>addToCart(b.dataset.add))})}
function renderProductDetail(){const el=$("#productDetail");if(!el)return;const id=new URLSearchParams(location.search).get("id");const p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];document.title=`${p.name} | Extended Muse`;el.innerHTML=`<div><img class="detail-photo" src="${p.image}" alt="${p.name}"></div><div class="detail-info"><p class="eyebrow">${p.category.toUpperCase()}</p><h1>${p.name}</h1><div class="detail-price">${money(p.price)}</div><p>${p.description}</p><p>♡ Carefully selected for the muse in you.</p><div class="quantity-row"><label for="productQty">QUANTITY</label><input id="productQty" type="number" min="1" max="10" value="1"></div><button class="btn" id="detailAdd">ADD TO BAG →</button><div class="notice">Shipping and delivery options are confirmed at checkout. Product availability and final pricing should be verified before launch.</div><a href="shop.html" class="policy-links">← CONTINUE SHOPPING</a></div>`;$("#detailAdd").addEventListener("click",()=>{const qty=Math.max(1,Math.min(10,Number($("#productQty").value)||1));addToCart(p.id,qty)})}
function renderCartPage(){const body=$("#cartContent");if(!body)return;function paint(){const cart=getCart();const rows=cart.map(item=>{const p=PRODUCTS.find(x=>x.id===item.id);if(!p)return"";return `<tr><td><div class="cart-item-name"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><br><small>${p.category}</small></div></div></td><td>${money(p.price)}</td><td><input class="qty-input" type="number" min="1" max="10" value="${item.qty}" data-qty="${p.id}" aria-label="Quantity for ${p.name}"></td><td>${money(p.price*item.qty)}</td><td><button class="remove-link" data-remove="${p.id}">Remove</button></td></tr>`}).join("");if(!cart.length){body.innerHTML=`<div class="empty-state"><h2>Your bag is waiting for something lovely.</h2><p>Explore our hair collections to find your next look.</p><a class="btn" href="shop.html">SHOP THE COLLECTION →</a></div>`;return}const subtotal=cart.reduce((s,i)=>s+(PRODUCTS.find(p=>p.id===i.id)?.price||0)*i.qty,0);body.innerHTML=`<div class="table-wrap"><table class="cart-table"><thead><tr><th>PRODUCT</th><th>PRICE</th><th>QTY</th><th>TOTAL</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><div class="cart-bottom"><div class="cart-total">Subtotal: ${money(subtotal)}</div><p>Shipping and taxes are calculated at checkout.</p><a class="btn" href="checkout.html">PROCEED TO CHECKOUT →</a><a href="shop.html">CONTINUE SHOPPING</a></div>`;$$("[data-remove]",body).forEach(b=>b.addEventListener("click",()=>{saveCart(getCart().filter(i=>i.id!==b.dataset.remove));paint()}));$$("[data-qty]",body).forEach(inp=>inp.addEventListener("change",()=>{const qty=Math.max(1,Math.min(10,Number(inp.value)||1));const c=getCart();const item=c.find(i=>i.id===inp.dataset.qty);if(item)item.qty=qty;saveCart(c);paint()}))}paint()}
function renderCheckout(){const summary=$("#checkoutSummary");if(!summary)return;const cart=getCart();if(!cart.length){summary.innerHTML=`<p>Your bag is empty. <a href="shop.html">Shop the collection</a>.</p>`;$("#placeOrder")?.setAttribute("disabled","disabled");return}const subtotal=cart.reduce((s,i)=>s+(PRODUCTS.find(p=>p.id===i.id)?.price||0)*i.qty,0);summary.innerHTML=cart.map(i=>{const p=PRODUCTS.find(p=>p.id===i.id);return p?`<p>${p.name} × ${i.qty}<strong style="float:right">${money(p.price*i.qty)}</strong></p>`:""}).join("")+`<hr><p><strong>Subtotal</strong><strong style="float:right">${money(subtotal)}</strong></p><small>Shipping/tax and payment confirmation must be configured before accepting real orders.</small>`;$("#checkoutForm")?.addEventListener("submit",e=>{e.preventDefault();const status=$("#checkoutStatus");if(!e.currentTarget.reportValidity())return;const order={reference:"EM-"+Date.now().toString().slice(-8),createdAt:new Date().toISOString(),customer:Object.fromEntries(new FormData(e.currentTarget).entries()),items:cart,subtotal};localStorage.setItem("em-last-order",JSON.stringify(order));status.innerHTML=`<p class="form-success">Your order details have been captured in this browser as a demo. Reference: <strong>${order.reference}</strong>. No payment has been taken and the store is not yet connected to a payment provider or order database.</p>`;saveCart([]);$("#placeOrder").disabled=true;})}
function setupShared(){updateCartCount();$("[data-menu]")?.addEventListener("click",()=>{$("#mobileDrawer")?.classList.add("open");$("#mobileDrawer")?.setAttribute("aria-hidden","false")});$("[data-close-menu]")?.addEventListener("click",()=>{$("#mobileDrawer")?.classList.remove("open");$("#mobileDrawer")?.setAttribute("aria-hidden","true")});$$(".mobile-drawer>a").forEach(a=>a.addEventListener("click",()=>$("#mobileDrawer")?.classList.remove("open")));$("[data-search]")?.addEventListener("click",()=>$("#searchLayer")?.classList.add("open"));$("[data-close-search]")?.addEventListener("click",()=>$("#searchLayer")?.classList.remove("open"));$("#searchLayer")?.addEventListener("click",e=>{if(e.target.id==="searchLayer")e.currentTarget.classList.remove("open")});$$("[data-newsletter]").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();form.querySelector(".form-message")?.replaceChildren(document.createTextNode("THANK YOU — YOU'RE ON THE LIST."));form.reset()}));document.addEventListener("keydown",e=>{if(e.key==="Escape"){ $("#mobileDrawer")?.classList.remove("open");$("#searchLayer")?.classList.remove("open")}})}
document.addEventListener("DOMContentLoaded",()=>{setupShared();renderProducts();renderProductDetail();renderCartPage();renderCheckout()});
